gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#12ba58"
      - "bold"
    inactiveBorderColor:
      - "#5f92b9"
    searchingActiveBorderColor:
      - "#FF8800"
      - "bold"
    optionsTextColor:
      - "#22ECDB"
    selectedLineBgColor:
      - "#222844"
    cherryPickedCommitFgColor:
      - "#111422"
    cherryPickedCommitBgColor:
      - "#F38CEC"
    markedBaseCommitFgColor:
      - "#111422"
    markedBaseCommitBgColor:
      - "#ffd94c"
    unstagedChangesColor:
      - "#ff4319"
    defaultFgColor:
      - "#c0caf5"
